### ISSUE TITLE
Question about batch size

### ISSUE THREAD

**Issue by Na-Z** [kaixin96/PANet#10]
Hi Kaixin,

May I know why the batch size is set to 1? Did you try larger batch size in your experiments, and will it have any effect?

Thanks.

**Comment by kaixin96** [comment]
Hi @Na-Z , setting batch size to 1 is following SG-one's protocol. We tried larger batch size(e.g. 4), but the performance gain is little.

**Comment by Na-Z** [comment]
I see. Thank you.
