### ISSUE TITLE
How can generate the qualitative results as in your paper ?

### ISSUE THREAD

**Issue by alex-marked** [kaixin96/PANet#11]
Hello,
Thank you for your nice work.
I am new in this area, my question is how can I obtain the qualitative results as in your paper Figure 3/4 ?

Thank you,
Alex ~

**Comment by kaixin96** [comment]
Hi @Alex-dong , you can train the model and test it on unseen images. The model will give you segmentation results. By overlaying the segmentation prediction with original images you can get figures like Figure 3/4.

**Comment by alex-marked** [comment]
OK
Thanks for your reply, I will try.
Best wishes ~

**Comment by t-sh99** [comment]
Hi @alex-marked, have you successfully obtained the qualitative results on unseen images?  How did you implement it?  Thank you
