### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by lxtGH** [kaixin96/PANet#16]
Hi Thank for open sourced code.  How long the trainig time will be ?  @kaixin96

**Comment by kaixin96** [comment]
Hi @lxtGH , it depends on the task. For 1-way 1-shot task on VOC, training takes about 3 hours on a GTX Titan X.

**Comment by LiheYoung** [comment]
Hi @kaixin96 , how long it takes when training without PAR? Are 30,000 steps still enough?

**Comment by kaixin96** [comment]
@LiheYoung I have tried 90000 steps before, the performance difference is little.

**Comment by kaixin96** [comment]
I’m closing this issue because it has been inactive for a while. Feel free to reopen if you have questions. Thank you.
