### ISSUE TITLE
Can't train the accuracy of the paper

### ISSUE THREAD

**Issue by LiGa0507** [kaixin96/PANet#17]
First of all, thank you very much for your open source code.
And I have a question for you. The mean-IoU of 1-way 1-shot segmentation on PASCAL-5i dataset in your paper is 48.1 , but the result of my training with your code is 41.9 .Do you have any suggestions or tricks for me? Look forward to your reply.

**Comment by kaixin96** [comment]
Hi @LiGa0507 , can you check which split does not match the reported performance? Thank you.

**Comment by LiGa0507** [comment]
I see where the problem is, thank you!

**Comment by tymatfd** [comment]
I cannot get the reported result too. Here's my final result 

INFO - main - ----- Final Result -----
INFO - main - classIoU mean: [0.56912405 0.50470607 0.50892423 0.32237848 0.16499783]
INFO - main - classIoU std: [0.02153639 0.02453332 0.02968146 0.01232205 0.02166889]
INFO - main - meanIoU mean: 0.4140261347733086
INFO - main - meanIoU std: 0.007181320264279855
INFO - main - classIoU_binary mean: [0.88718143 0.43176332]
INFO - main - classIoU_binary std: [0.00223838 0.00538581]
INFO - main - meanIoU_binary mean: 0.6594723762116546
INFO - main - meanIoU_binary std: 0.0026686067206232217
INFO - PANet - Completed after 0:26:07

Model is trained under default settings. How did you problem fixed? @LiGa0507, thanks for reply

**Comment by CLCxxx** [comment]
I also have this question 。could you tell me how did you fix this problem when you are free？thanks

**Comment by CLCxxx** [comment]
I find the problem，thx
