### ISSUE TITLE
Trained weights of the model

### ISSUE THREAD

**Issue by ahyunSeo** [kaixin96/PANet#2]
Hello,

Thank you for your work.

I would like to test your model on the other validation settings.

Could you provide the trained weights of your model?

Ahyun Seo

**Comment by kaixin96** [comment]
Hi Ahyun Seo, I have uploaded the trained models for 1-way 5-shot task on VOC to [Google drive](https://drive.google.com/drive/folders/1N00R9m9qe2rKZChZ8N7Hib_HR2HGtXHp?usp=sharing). Thank you.

Best,
Kaixin
