### ISSUE TITLE
Minor typo in comments

### ISSUE THREAD

**Issue by k0nen** [kaixin96/PANet#21]
Hello, and first of all thank you for the open source code.
I believe that the size of `fore_mask` and `back_mask` is `Wa x Sh x B x H x W`, not `Wa x Sh x B x H' x W'`. Please correct me if I'm wrong.

https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/models/fewshot.py#L64-L67

**Comment by kaixin96** [comment]
Hi @k0nen , thanks for pointing it out. It is a typo.

Best regards
