### ISSUE TITLE
Pascal VOC 2012 images

### ISSUE THREAD

**Issue by phuongchi911** [kaixin96/PANet#27]
Hi Kaixin, thank you for the source code. May I ask if you have any suggestion to download the images dataset? I tried to download them from the source link (http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar) but its site can never be reached and it got timed out all the times. I tried to search for other sources but they all reload back to the original link.

I know from the link you provided I can have all the masks.

Sorry if this question troubles you as this is my very first time working on this dataset. Thanks in advance.

**Comment by phuongchi911** [comment]
sorry i could download already. Sorry for the troublesome. Turned out has to wait for at least 10 mins for website to load it

**Comment by kaixin96** [comment]
Hi @phuongchi911, you may try this [mirror link](https://pjreddie.com/projects/pascal-voc-dataset-mirror/) (provided by the  author of YOLO).
