### ISSUE TITLE
 'SBD' folder  -sbd_instance_process.py

### ISSUE THREAD

**Issue by phuongchi911** [kaixin96/PANet#28]
Hi Kaixin sorry to trouble u. May i ask what is your 'SBD' folder and how i can get it? Sorry if i missed out something. From my undertanding it seemed u already have the SBD folder in place and process them and save them to`SegmentationClassAug` folder. Thank you very much.

`sbd_instance_process.py`

```This snippet processes SBD instance segmentation data
and transform it from .mat to .png. Then transformed
images will be saved in VOC data folder. The name of
the new folder is "SegmentationObjectAug"
```

**Comment by kaixin96** [comment]
Hi @phuongchi911 , the segmentation masks in `SegmentationClassAug` folder is downloaded from [here](https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0). I only process SBD data for generating instance-level masks. You may download the dataset from [here](http://home.bharathh.info/pubs/codes/SBD/download.html) and use the folder `benchmark_RELEASE/dataset` as SBD folder.

Thank you.

**Comment by phuongchi911** [comment]
> Hi @phuongchi911 , the segmentation masks in `SegmentationClassAug` folder is downloaded from [here](https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0). I only process SBD data for generating instance-level masks. You may download the dataset from [here](http://home.bharathh.info/pubs/codes/SBD/download.html) and use the folder `benchmark_RELEASE/dataset` as SBD folder.
> 
> Thank you.

Thanks so much for the details. Yes i have downloaded your SegmentationClassAug. May I ask if my data only has the masks photos like in the folder SegmentationClass, is it required to transform them to the SBD data? Thanks so much for the advise.

**Comment by kaixin96** [comment]
Basically the data in the Google Drive is all you need to run the experiments.

`sbd_instance_process.py` is only needed when you already have SBD data and don't want to download large files from Google Drive. Then you can use it to transform the SBD data format (.mat) into VOC format (PNG image with mode 'P'). The code in this repo uses VOC format masks.

Regarding your questions, it is not needed to transform them to the SBD data.

Thank you.

**Comment by phuongchi911** [comment]
Hi Kaixin.

Sorry me again. I would like to confirm my understanding from your paper on your testing set creation. May you kindly correct me if i am wrong? So from my understanding, there still be a chance that your testing will contain classes that overlap with your training set. May you advise if my understanding correctly?

**Comment by kaixin96** [comment]
I’m closing this issue because it has been inactive for a while. Feel free to reopen if you have questions. Thank you.
