### ISSUE TITLE
Cuda out of memory error

### ISSUE THREAD

**Issue by sheeba41** [kaixin96/PANet#31]
Hi @kaixin96 I was trying to run this code, and I ended up with a out of memory error:
`RuntimeError: CUDA out of memory. Tried to allocate 340.00 MiB (GPU 0; 1.96 GiB total capacity; 946.64 MiB already allocated; 23.38 MiB free; 1.33 GiB reserved in total by PyTorch)`

I noticed that the batch size is already 1 so I cannot reduce it further, is there a workaround?

Or is there any way I can use an interactive shell like colab to run it? because sacred doesnt support interactive environments afaik.

Your help would be greatly appreciated.

**Comment by kaixin96** [comment]
Hi @sheeba41 , 2GB might be too small for training. I am afraid there is not a workaround. You can use interactive shell to run it, though some code tweaks are needed. Thank you.

**Comment by kaixin96** [comment]
I’m closing this issue because it has been inactive for a while. Feel free to reopen if you have questions. Thank you.
