### ISSUE TITLE
Dataset source

### ISSUE THREAD

**Issue by Hardcandies** [kaixin96/PANet#32]
Hi, kaixin:
I can't find 'SegmentationClassAug' and file 'segmentation' in PASCAL or SBD.
PASCAL: http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html
SBD: http://home.bharathh.info/pubs/codes/SBD/download.html

Where did you download it and what is the source of this dataset?

jachymchen

**Comment by roywithfiringblade** [comment]
https://www.sun11.me/blog/2018/how-to-use-10582-trainaug-images-on-DeeplabV3-code/

**Comment by kaixin96** [comment]
Hi @Hardcandies , please check out README for the download link of folder `SegmentationClassAug` and folder `segmentation`.

**Comment by kaixin96** [comment]
Thank @704051419 for sharing the post which explains how `SegmentationClassAug` is built.

**Comment by Hardcandies** [comment]
@704051419 @kaixin96 Thank you.
