### ISSUE TITLE
Hardware information

### ISSUE THREAD

**Issue by ponpon010548** [kaixin96/PANet#33]
Hi! I am interesting to your awesome work but having limited hardware resource.
May I ask you about CPU and GPU(s) information? Thanks!

**Comment by kaixin96** [comment]
Hi @ponpon010548 , most experiments can be run on a single TITAN X GPU. I didn't monitor CPU usage but common desktop CPU (i5 or i7) should be ok. Thank you.

**Comment by ponpon010548** [comment]
Hi @kaixin96, got it. Thanks for your prompt reply!
