### ISSUE TITLE
Regarding the Data Splits 

### ISSUE THREAD

**Issue by ahatamiz** [kaixin96/PANet#34]
Hello, thanks for publicly sharing the code of your paper. I was going over the config.py file to see if the default setting match what is reported in the paper, but noticed that `n_runs = 5`. Shouldn't it be set to 4 as the reported accuracy is apparently for 4 splits ?  

I am under the assumption that for each run, the number reported in the paper (e.g. split-1 for run 0, split-2 for run 1 etc.) is the  `meanIoU` as printed in the outputs of test.py. And by setting `label_sets = 0` , one should be able to run the inference on the same splits as reported in the paper ( and seemingly by setting `n_runs = 4` as commented in the above. I Would appreciate some clarification.

**Comment by kaixin96** [comment]
Hi @ahatamiz , `label_sets = 0, 1, 2, 3` correspond to split-1, 2, 3, 4. `n_runs = 5` means 5 runs with different random seeds (but same split) and each run consists of 1000 testing episodes. This is meant to make the results more stable, as mentioned in Section 4.1 of our paper. Thank you.

**Comment by ahatamiz** [comment]
@kaixin96  Thank you. It makes sense.
