### ISSUE TITLE
Question about datasets.

### ISSUE THREAD

**Issue by Liurchen** [kaixin96/PANet#35]
Hi @kaixin96 
I can't found the JPEGImage folder, as the error information shows:
```python
FileNotFoundError: [Errno 2] No such file or directory: './data/VOCdevkit/VOC2012/JPEGImages/2011_000997.jpg'
```
Where can I find the whole datasets?
Thanks.

**Comment by kaixin96** [comment]
Hi @Liurchen , JPEGImage folder is in VOC dataset. You may download it from the [official site](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/) or [mirror site](https://pjreddie.com/projects/pascal-voc-dataset-mirror/). Thank you.

**Comment by Liurchen** [comment]
Thanks for replying.
