### ISSUE TITLE
**_config in train.py optimizer definition

### ISSUE THREAD

**Issue by ruohuali** [kaixin96/PANet#38]
Hello
Why in train.py's optimizer definition **_config is used instead of _config? 
`optimizer = torch.optim.SGD(model.parameters(), **_config['optim'])`
This caused error when I tried to run train.py
`    optimizer = torch.optim.SGD(model.parameters(), **_config['optim'])
KeyError: 'optim'
`
Thx for the help!

**Comment by DpDark** [comment]
Hello, I have the same problem. How did you solve it？

**Comment by 2679622694** [comment]
I have the same question

**Comment by sharmaannapurna** [comment]
HI, I am getting the same error when I tried to run the code. Any workaround?

**Comment by ruohuali** [comment]
I vaguely recall that it was a mistake about using wrong setup in config.py (I used test when it should be train or something like that).
