### ISSUE TITLE
Some questions about the dataloader

### ISSUE THREAD

**Issue by lailvlong** [kaixin96/PANet#6]
https://github.com/kaixin96/PANet/blob/c248b2542e2ae1906d11c85b493bc9000773d5fd/dataloaders/common.py#L155-L159

In this sample operation, the 'k' is set to be 'n_elements'. I think the 'k' here should be the number of class, but 'n_elements' is the number of images per class. Is it wrong?

**Comment by kaixin96** [comment]
Hi @lailvlong,

This line is actually not used. Sorry, the data loading code is a little bit messy. `n_elements` here is expected to be an integer.

For all experiments, code in [line 147](https://github.com/kaixin96/PANet/blob/master/dataloaders/common.py#L147) is used instead.

Hope this clarifies. Thank you.

**Comment by kaixin96** [comment]
I plan to update the data loading part using [torchmeta](https://github.com/tristandeleu/pytorch-meta). Stay tuned :)

**Comment by lailvlong** [comment]
> Hi @lailvlong,
> 
> This line is actually not used. Sorry, the data loading code is a little bit messy. `n_elements` here is expected to be an integer.
> 
> For all experiments, code in [line 147](https://github.com/kaixin96/PANet/blob/master/dataloaders/common.py#L147) is used instead.
> 
> Hope this clarifies. Thank you.

thanks for your replying!

**Comment by kaixin96** [comment]
update: rewriting data loading in torchmeta is on my todo list but currently not top 1, sorry :(

You may want to subscribe to [this issue](https://github.com/tristandeleu/pytorch-meta/issues/29).

**Comment by lailvlong** [comment]
`https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/dataloaders/customized.py#L206`
Hello! According to my comprehension, the _n_elements_ here is the number of selected images per class and it should change in every sample. However, here it is fixed. Does it matter?

**Comment by lailvlong** [comment]
https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/dataloaders/customized.py#L206
Hello! According to my comprehension, the n_elements here is the number of selected images per class and it should change in every sample. However, here it is fixed. Does it matter?

**Comment by lailvlong** [comment]
https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/dataloaders/customized.py#L206-L208
Hello! According to my comprehension, the _n_elements_ here is the number of the selected images per class and it should change in every sample. However, it is fixed. Does it matter?

**Comment by kaixin96** [comment]
Hi @lailvlong , you are right. The number of selected images per class is fixed. But it is ok because the order of the classes is random.
https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/dataloaders/common.py#L148-L149
For example, considering a 2-way 5-shot task on the first split, `n_elements` could be `[5, 6]` (`n_queries=1)`. These numbers do not correspond to particular classes. The classes sampled could be `[bicycle, boat]` or `[boat, bicycle]`. 

Hope this clarifies.

Thank you.

**Comment by lailvlong** [comment]
> Hi @lailvlong , you are right. The number of selected images per class is fixed. But it is ok because the order of the classes is random.
> https://github.com/kaixin96/PANet/blob/39815f7546f34d6b1055865a4b323c1da6984524/dataloaders/common.py#L148-L149
> 
> 
> For example, considering a 2-way 5-shot task on the first split, `n_elements` could be `[5, 6]` (`n_queries=1)`. These numbers do not correspond to particular classes. The classes sampled could be `[bicycle, boat]` or `[boat, bicycle]`.
> Hope this clarifies.
> 
> Thank you.

Yes, i get what you mean. However, when the _n_queries_ != 1, it will matter. For example, in a 2-way 1-shot task and _n_queries_ == 5, the ramdom function fix the _n_elements_ to be [3,4], then the _n_elements_ is always [3,4] but never to be [1,6] and [2,5].

**Comment by kaixin96** [comment]
Yes, that's a bug. Thanks for pointing it out. I missed the `n_queries != 1` case.

**Comment by Meoooww** [comment]
> I plan to update the data loading part using [torchmeta](https://github.com/tristandeleu/pytorch-meta). Stay tuned :)

Did you update? I don't see it in the code （22.07.16）Thank you very much for your update maintenance

**Comment by kaixin96** [comment]
@Meoooww I no longer work on few shot segmentation and will not update it, sorry.
