### ISSUE TITLE
sacred.utils.ConfigAddedError

### ISSUE THREAD

**Issue by chentao2016** [kaixin96/PANet#7]
Thanks for your work.

I ran your code and got the following error.  Could you give me some clue to solve it?
sacred.utils.ConfigAddedError: Added new config entry that is not used anywhere
Conflicting configuration values:
  model.sparse=False

**Comment by kaixin96** [comment]
Hi @chentao2016, it is an error in `sacred`. Deleting `model.sparse=False` from the `sh` script should work.

I forgot to remove this redundant args. Will update the repo soon.
